version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: "database"
    ports:
      - "5432:5432"
    environment:
      -POSTGRES_DB=postgres
      -POSTGRES_USER=postgres
      -POSTGRES_PASSWORD=123
    networks:
      fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data
  web:
    build: .
    container_name: "Snippet07box"
    environment:
      -DB_USERNAME: "postgres"
      -DB_PASSWORD: "123"
      -DB_DB: "Snippet07box"
      -DB_HOST: "db"
      -DB_TABLE: "snippets"
      -DB_PORT: "5432"
    depends_on:
      - db
    networks:
      - fullstack
    ports:
      - "4000:4000"
volumes:
  database_postgres:
networks:
  fullstack:
    driver: bridge